#!/usr/bin/python

import xml.etree.ElementTree as ET
import sys

def main(argv):
	inputfile = ''
	outputfile = ''
	
	if len(sys.argv) != 3:
		print 'Error - missing arguments \n'
		print 'Usage: python NmapXMLtoCSV.py <inputfile> <outputfile>'
		sys.exit(2)
	inputfile = argv[1]
	outputfile = argv[2]

	
	try:
		tree = ET.parse(inputfile)
		root = tree.getroot()
	except ParseError as e:
		print "Parse error({0}): {1}".format(e.errno, e.strerror)
		sys.exit(2)
	except:
		print "Unexpected error:", sys.exc_info()[0]
		sys.exit(2)
	
	fo = open(outputfile, 'w')
	out = "ip" + ',' + "hostname" + ',' + "port" + ',' + "protocol" + ',' + "service" + ',' + "version" + '\n'
	fo.write (out)
	
	for host in root.findall('host'):
		ip = host.find('address').get('addr')
		hostname = ""
		if host.find('hostnames').find('hostname') is not None:
			hostname = host.find('hostnames').find('hostname').get('name')
		for port in host.find('ports').findall('port'):
			protocol = port.get('protocol')
			if protocol is None:
				protocol = ""
			portnum = port.get('portid')
			if portnum is None:
				portnum = ""
			service = port.find('service').get('name')
			if service is None:
				service = ""
			version = port.find('service').get('product')
			if version is None:
				version = ""
			out = ip + ',' + hostname + ',' + portnum + ',' + protocol + ',' + service + ',' + version + '\n'
			fo.write (out)
	
	fo.close()
	
if __name__ == "__main__":
   main(sys.argv)
